"""skills and job_skills schema

Revision ID: 288898034cae
Revises: fb5a5c40c7e7
Create Date: 2025-12-24 12:29:21.413162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288898034cae'
down_revision: Union[str, Sequence[str], None] = 'fb5a5c40c7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_postings', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('job_postings', 'province',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_job_postings_country'), 'job_postings', ['country'], unique=False)
    op.create_index(op.f('ix_job_postings_role_category'), 'job_postings', ['role_category'], unique=False)
    op.create_index('ix_job_skills_job_id', 'job_skills', ['job_id'], unique=False)
    op.create_index('ix_job_skills_skill_id', 'job_skills', ['skill_id'], unique=False)
    op.drop_constraint(op.f('job_skills_skill_id_fkey'), 'job_skills', type_='foreignkey')
    op.drop_constraint(op.f('job_skills_job_id_fkey'), 'job_skills', type_='foreignkey')
    op.create_foreign_key(None, 'job_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_skills', 'job_postings', ['job_id'], ['id'], ondelete='CASCADE')
    op.add_column('skills', sa.Column('slug', sa.String(length=64), nullable=False))
    op.add_column('skills', sa.Column('category', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.drop_column('skills', 'category')
    op.drop_column('skills', 'slug')
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.create_foreign_key(op.f('job_skills_job_id_fkey'), 'job_skills', 'job_postings', ['job_id'], ['id'])
    op.create_foreign_key(op.f('job_skills_skill_id_fkey'), 'job_skills', 'skills', ['skill_id'], ['id'])
    op.drop_index('ix_job_skills_skill_id', table_name='job_skills')
    op.drop_index('ix_job_skills_job_id', table_name='job_skills')
    op.drop_index(op.f('ix_job_postings_role_category'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_country'), table_name='job_postings')
    op.alter_column('job_postings', 'province',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('job_postings', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_postings', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
