"""add source ids and salary fields

Revision ID: fb5a5c40c7e7
Revises: 297dec612c34
Create Date: 2025-12-21 16:40:34.330652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5a5c40c7e7'
down_revision: Union[str, Sequence[str], None] = '297dec612c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_raw', sa.String(length=255), nullable=True))
    op.add_column('job_postings', sa.Column('source_name', sa.String(length=100), nullable=False))
    op.add_column('job_postings', sa.Column('source_job_id', sa.String(length=500), nullable=False))
    op.create_index(op.f('ix_job_postings_city'), 'job_postings', ['city'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_date'), 'job_postings', ['posted_date'], unique=False)
    op.create_index(op.f('ix_job_postings_province'), 'job_postings', ['province'], unique=False)
    op.create_index(op.f('ix_job_postings_source_name'), 'job_postings', ['source_name'], unique=False)
    op.create_unique_constraint('uq_job_source', 'job_postings', ['source_name', 'source_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_source', 'job_postings', type_='unique')
    op.drop_index(op.f('ix_job_postings_source_name'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_province'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_date'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_city'), table_name='job_postings')
    op.drop_column('job_postings', 'source_job_id')
    op.drop_column('job_postings', 'source_name')
    op.drop_column('job_postings', 'salary_raw')
    op.drop_column('job_postings', 'salary_max')
    op.drop_column('job_postings', 'salary_min')
    # ### end Alembic commands ###
